"Reaction Aggressive" = "Monster is aggressive (growls, threatens, etc.)."
"Reaction Attack" = "Monster attacks."
"Reaction Cautious" = "Monster is cautious."
"Reaction Friendly" = "Monster is friendly."
"Reaction Neutral" = "Monster is neutral."
Round = "Round"

["Any town, village or city"]
description = "Hometown: Any town, village or city"
other = "Any town, village or city"

[Attributes]
description = "Character Attributes"
other = "STR Strength      %2d \t (%s Attack Roll [Melee, Unarmed], Damage Roll [Melee, Thrown], Open Doors, optional: Save: Paralysis, Turn to Stone)\nINT Intelligence  %2d \t (%s General Skills, %s, optional: Save vs. Mind Attacks)\nWIS Wisdom        %2d \t (%s Saving Throw vs. Spells)\nDEX Dexterity     %2d \t (%s Attack Roll [Thrown, Missiles], Armor Class, optional: Save: Wands, Dragon Breath)\nCON Constitution  %2d \t (%s Hit Points per XP Level, optional: Save: Poison)\nCHA Charisma      %2d \t (%s Reaction Adjustment from NPCs, %d max. Retainers, %d Retainer Morale)\n"

["Black Eagle Barony"]
description = "Hometown: Black Eagle Barony"
other = "Black Eagle Barony"

["Callarii Clan"]
description = "Ethnicity: Callarii Clan"
other = "Callarii Clan"

[CharacterRecordSheet]
description = "Character record sheet"
other = "Name:  %-32s \t Player:        %s\nClass: %-32s \t Alignment:     %s\nLevel: %2d %c (max. %2d) \t XP: %8d (%s%%) \t Next Level at: %d\n\n%s\n%s\nArmor Class: %3d \t Hitpoints: %d\nMovement:    %3d \t ThAC0:     %d\n\n%s\nArmor Proficiencies:  %s\nWeapon Proficiencies: %s\n\nBackground\n==========\nSex:    %-12s \t Age:    %4d (%s)\nHeight: %s \t\t Weight: %d cn (%d lb)\n%sStarting Money: %d GP\n\nSpecial Abilities\n=================\n%s\n%s\nDescriptions\n============\n%s\n%s\n"

["Church of Karameikos"]
description = "Church of Karameikos"
other = "Church of Karameikos"

["Church of Traladara"]
description = "Church of Traladara"
other = "Church of Traladara"

[Comfortable]
description = "Social Status: Comfortable"
other = "Comfortable"

[Common]
description = "Social Status: Common"
other = "Common"

["Cult of Halav"]
description = "Cult of Halav"
other = "Cult of Halav"

[Highforge]
description = "Hometown: Highforge"
other = "Highforge"

[Homestead]
description = "Hometown: Homestead"
other = "Homestead"

[Karameikos]
description = "Nation: Karameikos"
other = "Grandduchy of Karameikos"

[Kelvin]
description = "Hometown: Kelvin"
other = "Kelvin"

[Lord]
description = "Social Status: Lord"
other = "Lord"

["Mixed Traladaran/Thyatian"]
description = "Ethnicity: Mixed Traladaran/Thyatian"
other = "Mixed Traladaran/Thyatian"

[Penniless]
description = "Social Status: Penniless"
other = "Penniless"

[RetainerStats]
description = "Charisma Retainer Statistics"
other = "%d max. Retainers, %d Retainer Morale"

["Rifflian or Specularum"]
description = "Hometown: Elf"
other = "Rifflian or Specularum (Callarii) or Dymrak Woods (Vyalia)"

["Royal Family"]
description = "Social Status: Royal Family"
other = "Royal Family"

[Ruling]
description = "Social Status: Ruling"
other = "Ruling"

[SavingThrows]
description = "Character Saving Throws"
other = "Death Ray, Poison         %2d\nMagic Wands               %2d\nParalysis, Turn to Stone  %2d\nDragon Breath             %2d\nRod, Staff, Spells        %2d\n"

[Specularum]
description = "Hometown: Specularum"
other = "Specularum"

[Spell]
description = "Spell Description"
other = "%s\nRange: %s\nDuration: %s\nEffect: %s\n%s\n"

["Spell Description Header"]
description = "Header for Spell Descriptions"
other = "Spelldescriptions\n=================\n\n"

["Spell Description Obsidian Header"]
description = "Header for Spell Descriptions for Obsidian"
other = "### Spelldescriptions\n\n"

["Spell Level Header"]
description = "Header for Spell Level"
other = "Level %d\n--------\n"

["Spell Level Header (Obsidian)"]
description = "Header for Spell Level for Obsidian"
other = "#### Level %d\n"

["Spell Level Obsidian Header"]
description = "Header for Spell Level for Obsidian"
other = "#### Level %d\n\n"

["Spell List Header"]
description = "Header for Spell List"
other = "Spells\n======\n\n"

["Spell List Header (Obsidian)"]
description = "Header for Spell List for Obsidian"
other = "### Spells\n\n"

["Spell Obsidian"]
description = "Spell Description for Obsidian"
other = "##### %s\n|              |      |\n| :----------- | ---: |\n| **Range**    | %s |\n| **Duration** | %s |\n| ** Effect**  | %s |\n\n%s\n"

["Spell Slots Cleric"]
description = "Spell Slots for Cleric"
other = "Spell Slots\n-----------\n1st: %2d\n2nd: %2d\n3rd: %2d\n4th: %2d\n5th: %2d\n6th: %2d\n7th: %2d\n"

["Spell Slots Cleric (Obsidian)"]
description = "Spell Slots for Cleric for Obsidian"
other = "> [!infobox]\n> ### Spell Slots per Level\n>| Level    | \\#Spells |\n>| --- | ---: |\n>| 1st | %2d |\n>| 2nd | %2d |\n>| 3rd | %2d |\n>| 4th | %2d |\n>| 5th | %2d |\n>| 6th | %2d |\n>| 7th | %2d |\n"

["Spell Slots Magic-User"]
description = "Spell Slots for Magic-User"
other = "Spell Slots\n-----------\n1st: %2d\n2nd: %2d\n3rd: %2d\n4th: %2d\n5th: %2d\n6th: %2d\n7th: %2d\n8th: %2d\n9th: %2d\n"

["Spell Slots Magic-User (Obsidian)"]
description = "Spell Slots for Magic-User for Obsidian"
other = "> [!infobox]\n> ### Spell Slots per Level\n>| Level    | \\#Spells |\n>| --- | ---: |\n>| 1st | %2d |\n>| 2nd | %2d |\n>| 3rd | %2d |\n>| 4th | %2d |\n>| 5th | %2d |\n>| 6th | %2d |\n>| 7th | %2d |\n>| 8th | %2d |\n>| 9th | %2d |\n"

["Stronghollow Clan"]
description = "Ethnicity: Stronghollow Clan"
other = "Stronghollow Clan"

[Struggling]
description = "Social Status: Struggling"
other = "Struggling"

["Thief Skills"]
description = "Thief Skills"
other = "Open Locks:      %d%%\nFind Traps:      %d%%\nRemove Traps:    %d%%\nClimb Walls:     %d%%\nMove Silently:   %d%%\nHide In Shadows: %d%%\nPick Pockets:    %d%%\nHear Noise:      %d%%\n"

["Thief Skills (Obsidian)"]
description = "Thief Skills for Obsidian"
other = "|                 |      |\n| :-------------- | ---: |\n| Open Locks      | %d%% |\n| Find Traps      | %d%% |\n| Remove Traps    | %d%% |\n| Climb Walls     | %d%% |\n| Move Silently   | %d%% |\n| Hide In Shadows | %d%% |\n| Pick Pockets    | %d%% |\n| Hear Noise      | %d%% |\n"

[Thyatian]
description = "Ethnicity: Thyatian"
other = "Thyatian"

[Traladaran]
description = "Ethnicity: Traladaran"
other = "Traladaran"

["Turn Undead"]
description = "Turn Undead Table"
other = "Skeleton   \t %2s\nZombie     \t %2s\nGhoul      \t %2s\nWight      \t %2s\nWraith     \t %2s\nMummy      \t %2s\nSpectre    \t %2s\nVampire    \t %2s\nPhantom    \t %2s\nHaunt      \t %2s\nSpirit     \t %2s\nNightshade \t %2s\nLich       \t %2s\nSpecial    \t %2s\n"

["Turn Undead (Obsidian)"]
description = "Turn Undead Table for Obsidian"
other = "|           |     |\n| :--- | :---: |\n| Skeleton   | %2s |\n| Zombie     | %2s |\n| Ghoul      | %2s |\n| Wight      | %2s |\n| Wraith     | %2s |\n| Mummy      | %2s |\n| Spectre    | %2s |\n| Vampire    | %2s |\n| Phantom    | %2s |\n| Haunt      | %2s |\n| Spirit     | %2s |\n| Nightshade | %2s |\n| Lich       | %2s |\n| Special    | %2s |\n"

["Turn Undead Legend"]
description = "Turn Undead Legend Table"
other = "\n7, 9, or 11 number needed to turn successfully\nT           automatic turn, 2d6 Hit Dice of undead\nD           automatic Destroy, 2d6 Hit Dice of undead\nD+          automatic Destroy, 3d6 Hit Dice of undead\nD#          automatic Destroy, 4d6 Hit Dice of undead\n\n"

["Turn Undead Legend (Obsidian)"]
description = "Turn Undead Table Legend for Obsidian"
other = "\n>[!infobox]\n>| | |\n>| :---: | :--- |\n>| 7, 9, or 11 | number needed to turn successfully |\n>| T           | automatic turn, 2d6 Hit Dice of undead |\n>| D           | automatic Destroy, 2d6 Hit Dice of undead |\n>| D+          | automatic Destroy, 3d6 Hit Dice of undead |\n>| D#          | automatic Destroy, 4d6 Hit Dice of undead |\n\n"

["Very Wealthy"]
description = "Social Status: Very Wealthy"
other = "Very Wealthy"

["Village or Town (choice)"]
description = "Hometown: Village or Town (choice)"
other = "Village or Town (choice)"

["Vyalia Clan"]
description = "Ethnicity: Vyalia Clan"
other = "Vyalia Clan"

[Wealthy]
description = "Social Status: Wealthy"
other = "Wealthy"

[ac]
description = "AC"
other = "AC"

[can_write]
description = "Can read and write"
other = "Reads and writes (usually two) native languages"

[can_write_simple]
description = "Can write simple"
other = "Can write simple common words"

[cannot_read_write]
description = "Cannot read or write"
other = "Cannot read or write Common"

[cannot_speak]
description = "Cannot speak"
other = "Has trouble speaking, cannot read or write"

[chaotic]
description = "Chaotic"
other = "Chaotic"

[female]
description = "Female"
other = "Female"

[hp]
description = "HP"
other = "HP"

[karameikos_background]
description = "Karameikos Background"
other = "Ethnicity: %s\nSocial Status: %s %s\nHome: %s\n"

[lawful]
description = "Lawful"
other = "Lawful"

[male]
description = "Male"
other = "Male"

[neutral]
description = "Neutral"
other = "Neutral"

[other]
description = "Other"
other = "Other"

[roll]
description = "Roll"
other = "Roll"

[titled]
description = "Social Status: Titled"
other = "Titled"
